import OptionObject from "./objects/OptionObject";

export default (): OptionObject[] => {
  return [
    { number: 0, label: "Italiana" },
    { number: 1, label: "Mexicana" },
    { number: 2, label: "Española" },
    { number: 3, label: "Japonesa" },
    { number: 4, label: "China" },
    { number: 5, label: "Francesa" },
    { number: 6, label: "Americana" },
    { number: 7, label: "Vegetariana" },
    { number: 8, label: "Vegana" },
    { number: 9, label: "Sin gluten" },
    { number: 10, label: "Comida rápida" },
    { number: 11, label: "Gourmet" },
    { number: 12, label: "Internacional" },
    { number: 13, label: "Mariscos" },
    { number: 14, label: "Al aire libre" },
    { number: 15, label: "En familia" },
    { number: 16, label: "Para parejas" },
    { number: 17, label: "Romántica" },
    { number: 18, label: "Para grupos" },
    { number: 19, label: "Para llevar" },
    { number: 20, label: "Bar" },
    { number: 21, label: "Brunch" },
    { number: 22, label: "Desayuno" },
    { number: 23, label: "Almuerzo" },
    { number: 24, label: "Cena" },
    { number: 25, label: "Sushi" },
    { number: 26, label: "Postres" },
    { number: 27, label: "Pastelería" },
    { number: 28, label: "Helados" },
    { number: 29, label: "Barbacoa" },
    { number: 30, label: "Comida casera" },
    { number: 31, label: "Parrilla" },
  ];
};