import OptionObject from "./objects/OptionObject";

export default (): OptionObject<number>[] => {
  return [
    { value: 0, label: "Italiana" },
    { value: 1, label: "Mexicana" },
    { value: 2, label: "Española" },
    { value: 3, label: "Japonesa" },
    { value: 4, label: "China" },
    { value: 5, label: "Francesa" },
    { value: 6, label: "Americana" },
    { value: 7, label: "Vegetariana" },
    { value: 8, label: "Vegana" },
    { value: 9, label: "Sin gluten" },
    { value: 10, label: "Comida rápida" },
    { value: 11, label: "Gourmet" },
    { value: 12, label: "Internacional" },
    { value: 13, label: "Mariscos" },
    { value: 14, label: "Al aire libre" },
    { value: 15, label: "En familia" },
    { value: 16, label: "Para parejas" },
    { value: 17, label: "Romántica" },
    { value: 18, label: "Para grupos" },
    { value: 19, label: "Para llevar" },
    { value: 20, label: "Bar" },
    { value: 21, label: "Brunch" },
    { value: 22, label: "Desayuno" },
    { value: 23, label: "Almuerzo" },
    { value: 24, label: "Cena" },
    { value: 25, label: "Sushi" },
    { value: 26, label: "Postres" },
    { value: 27, label: "Pastelería" },
    { value: 28, label: "Helados" },
    { value: 29, label: "Barbacoa" },
    { value: 30, label: "Comida casera" },
    { value: 31, label: "Parrilla" },
  ];
};