import AmenityObject from "./objects/AmenityObject"

export default (): AmenityObject[] => {
  return [
    { name: "Bar/Salón", icon: "wine" },
    { name: "Wifi libre", icon: "wifi" },
    { name: "Parking", icon: "parking" },
    { name: "Wifi libre2", icon: "wifi" },
    { name: "Wifi libre3", icon: "wifi" },
    { name: "Wifi libre4", icon: "wifi" },
    { name: "Wifi libre5", icon: "wifi" },
    { name: "Wifi libre6", icon: "wifi" },
    { name: "Wifi libre7", icon: "wifi" },
    { name: "Wifi libre8", icon: "wifi" },
    { name: "Wifi libre9", icon: "wifi" },
    { name: "Wifi libre10", icon: "wifi" },
    { name: "Wifi libre11", icon: "wifi" },
    { name: "Wifi libre12", icon: "wifi" },
    { name: "Wifi libre13", icon: "wifi" },
    { name: "Wifi libre14", icon: "wifi" },
    { name: "Wifi libre15", icon: "wifi" },
    { name: "Wifi libre16", icon: "wifi" },
    { name: "Wifi libre17", icon: "wifi" },
    { name: "Wifi libre18", icon: "wifi" },
    { name: "Wifi libre19", icon: "wifi" },
    { name: "Wifi libre20", icon: "wifi" },
    { name: "Wifi libre21", icon: "wifi" },
    { name: "Wifi libre22", icon: "wifi" },
    { name: "Wifi libre23", icon: "wifi" },
    { name: "Wifi libre24", icon: "wifi" },
    { name: "Wifi libre25", icon: "wifi" },
    { name: "Wifi libre26", icon: "wifi" },
    { name: "Wifi libre27", icon: "wifi" },
  ];
};
