name: Pa'Ca UI build

on:
  push:
    branches:
      - feat_build

jobs:
  build-release:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.19.0
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Push bundle to release branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Deploy new bundle"
          git push --set-upstream origin HEAD:release
