name: Pa'Ca UI build

on:
  push:
    branches:
      - feat_bundle

jobs:
  build-and-deploy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci —legacy-peer-deps 
      - name: Build app
        run: npm run build
      - name: Push bundle to release branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Deploy new bundle"
          git push origin HEAD:release